import java.io.*;
import java.util.Random;

public class dataCreator {
    public static void main(String[] args) {
        createMyPage();
        createFriends();
        createAccessLogs();
    }

    public static void createAccessLogs() {
        File file = new File("AccessLog.csv");
        Random rand = new Random();
        int byWho, whatPage, accessTime;
        String accessType;
        String[] accessTypeList = {
                "The user viewed the page",
                "The user left a note on the page",
                "The user added a friendship at the page",
                "The user liked the page",
                "The user clicked a link on the page",
                "The user clicked a phone number on the page",
                "The user watched a video on the page",
                "The user loaded old photos on the page",
                "The user viewed the friends list on the page",
                "The user left a comment on the page"
        };
        int limit = 10000000;
        String[] descList = {""};
        try {
            FileWriter writer = new FileWriter("AccessLogs.csv");
            for (int i = 1; i <= limit; i++) {
                byWho = 1 + rand.nextInt(199999);
                whatPage = 1 + rand.nextInt(199999);
                accessTime = 1 + rand.nextInt(999999);
                accessType = accessTypeList[rand.nextInt(accessTypeList.length - 1)];
                writer.write(i + ", " + byWho + ", " + whatPage + ", " + accessType + ", " + accessTime + "\n");
            }
            writer.close();
        } catch (IOException e) {
            System.out.println("error");
        }
    }

    public static void createFriends() {
        File file = new File("Friends.csv");
        Random rand = new Random();
        int personID, myFriend, friendDate;
        String desc;
        int limit = 20000000;
        String[] descList = {"The user added a college-friend as a friend",
                "The user added a hometown-friend as a friend",
                "The user added a girlfriend as a friend",
                "The user added a boyfriend as a friend",
                "The user added a partner as a friend",
                "The user added a family member as a friend",
                "The user added a coach as a friend",
                "The user added a mentor as a friend",
                "The user added a professor as a friend",
                "The user added a student as a friend",
                "The user added a co-worker as a friend",
                "The user added a boss as a friend",
                "The user added a pet as a friend"
        };
        try {
            FileWriter writer = new FileWriter("Friends.csv");
            for (int i = 1; i <= limit; i++) {
                personID = 1 + rand.nextInt(199999);
                myFriend = 1 + rand.nextInt(199999);
                friendDate = 1 + rand.nextInt(999999);
                desc = descList[rand.nextInt(descList.length - 1)];
                writer.write(i + ", " + personID + ", " + myFriend + ", " + friendDate + ", " + desc + "\n");
            }
            writer.close();
        } catch (IOException e) {
            System.out.println("error");
        }
    }

    public static void createMyPage() {
        File file = new File("MyPage.csv");
        Random rand = new Random();
        String name, countryName, hobby;
        int countryCode;
        int limit = 200000;
        String[] nameList = {"Noah Faulkner",
                "Jensen Mcbride",
                "Liana Cervantes",
                "Eliezer Tate",
                "Omari Manning",
                "Clay Downs",
                "Karlie Bruce",
                "June Rollins",
                "Odin Mcpherson",
                "Coleman Baker",
                "Isis Poole",
                "Maximo Marquez",
                "Ramiro Small",
                "Jovanny Casey",
                "Esmeralda Frazier",
                "Tatum West",
                "Emilie Irwin",
                "Camren Dyer",
                "Claire Middleton",
                "Guillermo Young",
                "Uriel Flores",
                "Quinn Hughes",
                "Abbey Dickerson",
                "Lamont Duffy",
                "Elian Soto",
                "Leo Marshall",
                "Efrain Zuniga",
                "Elliana Stevenson",
                "Rene Franklin",
                "Kaitlin Mosley",
                "Luka Rosales",
                "Sherlyn Calderon",
                "Branson Downs",
                "Abel Tyler",
                "Bronson Norris",
                "Janiyah Horn",
                "Leia Brooks",
                "Phoenix Page",
                "Alana Payne",
                "Skylar Gardner",
                "Enrique Hardin",
                "Makaila Sherman",
                "Anabelle Foley",
                "Nicole Watson",
                "Eleanor Shea",
                "Rayne Green",
                "Georgia Villarreal",
                "Jesus Sawyer",
                "Reginald Bender",
                "Shirley Mora",
                "Simon Kent",
                "Yoselin Hoffman",
                "Luciana Boyle",
                "Ann Valentine",
                "Gwendolyn Sharp",
                "Jayvon Guerrero",
                "Harley Gallegos",
                "Neveah Russell",
                "Damari Knapp",
                "Lacey Osborn",
                "Kayleigh Horne",
                "Erica Baxter",
                "Dominick Douglas",
                "Kobe Downs",
                "Maggie Silva",
                "Van Kennedy",
                "Amani Maddox",
                "Ibrahim Woods",
                "Rihanna Burch",
                "Natalee Mcdaniel",
                "Alfonso Potter",
                "Leonel Suarez",
                "Kayley Ramos",
                "Zackery Caldwell",
                "Jazmine Medina",
                "Elliott Barker",
                "Koen Mcfarland",
                "Rebekah Moss",
                "Roselyn Rich",
                "Alondra Ellison",
                "Jorge Shelton",
                "Matias Sullivan",
                "Phillip Carr",
                "Jair Villanueva",
                "Chelsea Sheppard",
                "Mckenna Burch",
                "Kaliyah Escobar",
                "Haven Mcmahon",
                "Bella Wallace",
                "Nickolas Aguirre",
                "Lilly Robles",
                "Aubrey Dickerson",
                "Haylee Barajas",
                "Rylie Richards",
                "Miya Lloyd",
                "Eden Gardner",
                "Houston Adkins",
                "Freddy Novak",
                "Amiya Goodwin",
                "Muhammad Phillips",
                "Vance Wall",
                "Cindy Terrell",
                "Emery Rice",
                "Marley Hale",
                "Cristina Ashley",
                "Arjun Booker",
                "Damian Tanner",
                "Tyrese Burke",
                "Giselle Valencia",
                "Gillian Pacheco",
                "Siena Hatfield",
                "Tessa Suarez",
                "Arely Cain",
                "Deja Gonzalez",
                "Madeline Ashley",
                "Liana Barrera",
                "Junior Richardson",
                "Karsyn Frye",
                "Jaelyn Valencia",
                "Elijah Nixon",
                "Lance Schmidt",
                "Malaki Wagner",
                "Brennan Friedman",
                "Omar Vasquez",
                "Rebekah Mccoy",
                "Antoine Lucero",
                "Dixie Holt",
                "Khalil Hendrix",
                "Leslie Wagner",
                "Amanda Kirby",
                "Stella Brennan",
                "Jimena Bridges",
                "Cesar Mathews",
                "Joseph Colon",
                "Fletcher Maddox",
                "Pierce Branch",
                "Rodrigo Parks",
                "Destinee Arias",
                "Davis Holmes",
                "Lance Nicholson",
                "Dalia Lawrence",
                "Janae Blankenship",
                "Talon Acevedo",
                "Amiah Wagner",
                "Barbara Lamb",
                "Abagail Gates",
                "Jaiden Calderon",
                "Israel Hodge",
                "Jefferson Shepherd",
                "Dereon Price",
                "Marie Watkins",
                "Cameron Campbell",
                "Davis Stokes",
                "Shyann Hurley",
                "Salvador Stafford",
                "Rubi Bradley",
                "Alexzander Bond",
                "Derick Clements",
                "Nickolas Kelley",
                "Ariana Duffy",
                "Rory Hinton",
                "Skyler Rocha",
                "Shannon Frey",
                "Nathan Riddle",
                "Marcel Parker",
                "Mikaela Randall",
                "Cindy Lang",
                "Clara Lyons",
                "Kira Shaffer",
                "Jacquelyn Carpenter",
                "Messiah Zamora",
                "Shawn Jensen",
                "Brady Barrera",
                "Cynthia Mccoy",
                "Franklin Crane",
                "Madisyn Hall",
                "Danielle Turner",
                "Tristin Mata",
                "Elsie Atkinson",
                "Chase Mendoza",
                "Nayeli Ashley",
                "Caiden Day",
                "Eliezer Christian",
                "Solomon Mathews",
                "Craig Page",
                "Carsen Kent",
                "Jax Walker",
                "Trinity Byrd",
                "Kendall Short",
                "Quinn Zavala",
                "Emilio Lee",
                "Shaylee Kemp",
                "Grayson Mclean",
                "Rachael Tapia",
                "Kali Dixon",
                "Darryl Yoder",
                "Giana Andersen",
                "Johnathan Arias",
                "Kody Blake",
                "Hector French",
                "Declan Serrano",
                "Liberty Ortiz",
                "Elisha Fitzgerald",
                "Kristen Ward",
                "Ross Shannon",
                "Gretchen Ayala",
                "Peter Sullivan",
                "Dale Schneider",
                "Camron Nielsen",
                "Taniya Newman",
                "Aaron Estrada",
                "Alfred York",
                "Ronald Odom",
                "Gillian Villegas",
                "Tamara Harvey",
                "Hailie Sharp",
                "Jorden Waters",
                "Rolando Rivera",
                "Jadon Dunn",
                "Derick Roth",
                "Luka Mcpherson",
                "Joyce Wilkinson",
                "Sanaa Gonzales",
                "Kaeden Brooks",
                "Adrianna Sandoval",
                "Kenna Christensen",
                "Bailey Allen",
                "Pamela Lucero",
                "Reid Conner",
                "Giovanni West",
                "Osvaldo Odom",
                "Harmony Gillespie",
                "Jovanny Cook",
                "Elisabeth Pineda",
                "Parker Watson",
                "Talon Nelson",
                "Kian Stephenson",
                "Bianca Irwin",
                "Darryl Gilbert",
                "Santos Mcfarland",
                "Aliyah Mosley",
                "Josephine Hickman",
                "Jillian Wright",
                "Kendal Mosley",
                "Jayvion Whitehead",
                "Soren Black",
                "Rey Mccullough",
                "Sam Jensen",
                "Bridget Fuentes",
                "Jett Simon",
                "Kailyn Rowe",
                "Jordan Novak",
                "Destiney Mckay",
                "Gavyn Hahn",
                "Angelina Roberson",
                "Thaddeus Padilla",
                "Raiden Small",
                "Ariella Richardson",
                "Rudy Knapp",
                "Nathaniel Dodson",
                "Makai Mason",
                "Byron Fritz",
                "Sheldon Wu",
                "Fabian Pollard",
                "Zander Warren",
                "Laura Payne",
                "Gemma Mcdowell",
                "Essence Duffy",
                "Conor Hampton",
                "Gabriella Mcdaniel",
                "Brenna Ibarra",
                "Bruno Pratt",
                "Johanna Andersen",
                "Seth Kaufman",
                "Brandon Travis",
                "Jaliyah Carr",
                "Jadyn Webster",
                "Nathanael Robinson",
                "Isai Navarro",
                "Sean Hurst",
                "Bryanna Porter",
                "Cyrus Greene",
                "Belen Wright",
                "Arabella Burgess",
                "Martin Oneal",
                "Landin Quinn",
                "Dania Espinoza",
                "Mary Rosales",
                "Addison Wells",
        };
        String[] countryList = {"United Arab Emirates",
                "Afghanistan",
                "Antigua & Barbuda",
                "Netherlands Antilles",
                "Antarctica",
                "American Samoa",
                "Åland Islands",
                "Azerbaijan",
                "Bosnia & Herzegovina",
                "Bangladesh",
                "Burkina Faso",
                "St. Barthélemy",
                "Bouvet Island",
                "Congo - Kinshasa",
                "Congo - Brazzaville",
                "Switzerland",
                "Côte d’Ivoire",
                "Cook Islands",
                "Costa Rica",
                "Cape Verde",
                "Christmas Island",
                "Dominican Republic",
                "Western Sahara",
                "Falkland Islands",
                "Micronesia",
                "Faroe Islands",
                "United Kingdom",
                "French Guiana",
                "Guadeloupe",
                "Equatorial Guinea",
                "Guinea-Bissau",
                "Hong Kong SAR China",
                "Isle of Man",
                "Kyrgyzstan",
                "St. Kitts & Nevis",
                "North Korea",
                "South Korea",
                "Cayman Islands",
                "Kazakhstan",
                "Liechtenstein",
                "Luxembourg",
                "Montenegro",
                "St. Martin",
                "Madagascar",
                "Marshall Islands",
                "North Macedonia",
                "Myanmar (Burma)",
                "Macao SAR China",
                "Martinique",
                "Mauritania"};
        String[] hobbyList = {"Basketball",
                "D printing",
                "Aerial silk",
                "Airbrushing",
                "Amateur radio",
                "Aquascaping",
                "Barbershop Music",
                "Baton twirling",
                "Beatboxing",
                "Beer tasting",
                "Bell ringing",
                "Board/tabletop games",
                "Book restoration",
                "Brazilian jiu-jitsu",
                "Breadmaking",
                "Bullet journaling",
                "Calligraphy",
                "Candle making",
                "Candy making",
                "Car Spotting",
                "Card games",
                "Cheesemaking",
                "Clothesmaking",
                "Coffee roasting",
                "Collecting",
                "Communication",
                "Community activism",
                "Computer programming",
                "Confectionery",
                "Conlanging",
                "Construction",
                "Cosplaying",
                "Couch surfing",
                "Creative writing",
                "Crocheting",
                "Cross-stitch",
                "Crossword puzzles",
                "Cryptography",
                "Cue sports",
                "Decorating",
                "Digital arts",
                "Distro Hopping",
                "Do it yourself",
                "Drink mixing",
                "Electronic games",
                "Electronics",
                "Embroidery",
                "Entertaining",
                "Experimenting",
                "Fantasy sports",
                "Fashion design",
                "Feng shui decorating",
                "Filmmaking",
                "Fingerpainting",
                "Fishfarming",
                "Fishkeeping",
                "Flower arranging",
                "Furniture building",
                "Giving advice",
                "Glassblowing",
                "Gongfu tea",
                "Graphic design",
                "Gunsmithing",
                "Herp keeping",
                "Home improvement",
                "Homebrewing",
                "Houseplant care",
                "Hula hooping",
                "Hydrodipping",
                "Hydroponics",
                "Ice skating",
                "Jewelry making",
                "Jigsaw puzzles",
                "Journaling",
                "Knife making",
                "Knot tying"
        };

        try {
            FileWriter writer = new FileWriter("MyPage.csv");
            for (int i = 1; i <= limit; i++) {
                name = nameList[rand.nextInt(nameList.length - 1)];
                countryCode = 1 + rand.nextInt(countryList.length - 1);
                countryName = countryList[countryCode];
                hobby = hobbyList[rand.nextInt(hobbyList.length - 1)];
                writer.write(i + ", " + name + ", " + countryName + ", " + countryCode + ", " + hobby + "\n");
            }
            writer.close();
        } catch (IOException e) {
            System.out.println("error");
        }
    }
}
